### ISSUE TITLE
Error after build and start

### ISSUE THREAD

**Issue by Sakol538** [EugeneKruglei/solution#1]
Reference ticket https://stackoverflow.com/questions/73893029/angular-modular-f%c3%a9d%c3%a9ration-why-mfe1-app-module-tsroot-module-not-able-to-con/73898017?noredirect=1#comment130614044_73898017
As informed tried, with repo checking but unfortunately getting run time error 
![image](https://user-images.githubusercontent.com/3215032/194822535-09aed1d7-dda9-4abb-a1c0-572bec689dc1.png)

Error getting after build and start:
Error: Shared module is not available for eager consumption: 1327
    at __webpack_require__.m.<computed> (consumes:150:1)
    at __webpack_require__ (bootstrap:19:1)
    at 4497 (log.js:49:1)
    at __webpack_require__ (bootstrap:19:1)
    at sharing:45:1
    at __webpack_require__.m.<computed> (consumes:151:1)
    at __webpack_require__ (bootstrap:19:1)
    at 2643 (home.component.html:7:55)
    at Function.__webpack_require__ (bootstrap:19:1)
    at ZoneDelegate.invoke (zone.js:400:30)

**Comment by EugeneKruglei** [comment]
@Sakol538 reverted - sorry for long delay

**Comment by EugeneKruglei** [comment]
@Sakol538 what is unresolved?  show screenshots. On my machine it works.
